name: Pull Request Quality Checks
on:
  pull_request:
    types: [ opened, synchronize ]
    branches: [ main ]
jobs:
  run-qa:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Run qa
        run: |
          make dev
          make qa
